name: "Tests"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [pull_request]
jobs:
  build:
    name: Build & Unit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        tags: storage-dev
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Start storage
      run: |
        docker compose up -d
    
    - name: Unit Tests
      run: docker compose exec -T tests vendor/bin/phpunit --configuration phpunit.xml --debug --testsuite unit